spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://192.168.17.129:3306/bsbdj?useSSL=false&serverTimezone=GMT%2b8&useUnicode=true #打开自己设置编码集useUnicode不要设置characterEncoding 他不支持utf8mb4
    username: root
    password: 156967
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
    tomcat:
      init-s-q-l: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci #初始化设置编码集

mybatis:
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 80
pagehelper:
  helper-dialect: mysql
  #查询合理化 不足一页差一页，页码大于最后一页查询最后一页
  reasonable: true